Add ability to configure errorlog file path and mode
voxpupuli/puppet-proxysql pull request #153
Opened 2020-08-28 01:58 UTC by Anirudhra10

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2020-08-28 07:19 UTC, alexjfisher commented on manifests/init.pp
> +  String $errorlog_file = $proxysql::params::errorlog_file,
You could use `Stdlib::Unixpath` here.  Looks like `datadir` should be using a stdlib type too, but this was never added back after some historical fiasco where stdlib had to be removed. See https://github.com/voxpupuli/puppet-proxysql/issues/65

Also, the default should probably be based on `datadir`

```suggestion
Stdlib::Unixpath $errorlog_file = "${datadir}/proxysql.log"
```

2020-08-28 07:29 UTC, alexjfisher commented on manifests/init.pp
> +  Stdlib::Filemode $errorlog_file_mode = $proxysql::params::errorlog_file_mode,
Could you move the default from params.pp to here.  This is now preferred for non operating specific defaults as we want to move documentation to puppet-strings. (And another reminder to myself to get back and finish https://github.com/voxpupuli/puppet-proxysql/pull/127)

2020-08-28 07:29 UTC, alexjfisher commented on manifests/install.pp
> +  file { 'proxysql-errorlog-file':
I'd probably just use `$proxysql::errorlog_file` as the resource title and not use a separate `path` parameter.

2020-08-28 07:29 UTC, alexjfisher commented on manifests/install.pp
> +    group  => $proxysql::sys_group,
Would it make sense to have an `errorlog_file_group` parameter??  Just thinking about users who might have already been managing this file in their profiles.

That or maybe the default for the new `errorlog_file` could be `undef` and this resource wrapped in an `if $errorlog_file` conditional.

2020-08-28 07:55 UTC, mcrauwel commented
@Anirudhra10 keep in mind that the `errorlog` configuration setting is only available starting from ProxySQL v2.0.x.

Whereas ProxySQL v2 is the suggested version, v1.4.x is still available and supported... I don't believe specifying the configuration variable in a 1.4 config file will break anything (I believe it will just be ignored) but it might create confusion when Puppet sets the errorlog to something else and the file doesn't show up there...

2020-08-28 07:58 UTC, Anirudhra10 commented
@mcrauwel Noted, fair enough. Would it be helpful to mention this in the README alongside the errorlog params?

2020-08-28 08:01 UTC, Anirudhra10 commented on manifests/init.pp
> +  String $errorlog_file = $proxysql::params::errorlog_file,
👍 I will update the datatype for `errorlog_file` and leave out `datadir` for a different day..unless you want me to address it in this PR.

2020-08-28 08:04 UTC, mcrauwel commented
@Anirudhra10 I would do that for sure... I would also set the default to a empty or null value when ProxySQL version is < 2.0.0

I'm wondering if should call a `warning()` or even a `fail()` when the errorlog setting is non empty and version < 2.0.0, any thoughts @alexjfisher ?

2020-08-28 08:08 UTC, Anirudhra10 commented on manifests/install.pp
> +    group  => $proxysql::sys_group,
To avoid impacting current users, it would be better to add `errorlog_file_group ` param. That would allow them to backfill the group via this param and not see any changes on their log files.

2020-08-28 08:50 UTC, Anirudhra10 commented
@alexjfisher I have added params to define both the owner and group for errorlog_file.
@mcrauwel I am setting `errorlog_file` defaults to 1.x and 2.x

2020-08-29 06:08 UTC, bastelfreak approved these changes

2020-08-29 06:09 UTC, bastelfreak reviewed
can you add some tests that verifies that the file resource appears in the catalog?

2020-08-29 09:09 UTC, alexjfisher commented on manifests/init.pp
> +    /^2/ => "${datadir}/proxysql.log",
since this is the default anyway, why not keep it simple and default to `undef` in all cases.

2020-08-29 09:13 UTC, alexjfisher commented on manifests/init.pp
> +    errorlog => $errorlog_file,
at the end of the `default_settings` hash add
```puppet
.filter |$key, $val| { $val =~ NotUndef }
```
to knock out `undef` values.

2020-08-29 09:15 UTC, alexjfisher requested changes

2020-08-29 09:15 UTC, alexjfisher commented on manifests/init.pp
> +#   Owner of the `errorlog_file`. Defaults to 'undef'. Available from ProxySQL v2.0.0
This doesn't (and shouldn't) default to `undef` though.

2020-08-29 09:23 UTC, alexjfisher commented
> I'm wondering if should call a `warning()` or even a `fail()` when the errorlog setting is non empty and version < 2.0.0, any thoughts @alexjfisher ?

Could do.  Since it's a new parameter, I'd go straight to `fail`.  Also, in my experience, not many people are constantly monitoring the puppetserver logs for warnings. (FWIW, https://forge.puppet.com/ipcrm/echo is good for issuing warnings too)

2020-08-29 20:30 UTC, Anirudhra10 commented on manifests/init.pp
> +    errorlog => $errorlog_file,
added..

2020-08-29 20:30 UTC, Anirudhra10 commented on manifests/init.pp
> +    /^2/ => "${datadir}/proxysql.log",
fixed..

2020-08-29 20:30 UTC, Anirudhra10 commented on manifests/init.pp
> +#   Owner of the `errorlog_file`. Defaults to 'undef'. Available from ProxySQL v2.0.0
also fixed

2020-08-30 10:34 UTC, alexjfisher approved these changes

2020-08-30 16:51 UTC, merged