Release 5.2.0 version
voxpupuli/puppet-proxysql pull request #154
Opened 2020-08-30 20:32 UTC by Anirudhra10

#### Pull Request (PR) description
- Release version 5.2.0.
- Minor fix in comments

#### This Pull Request (PR) fixes the following issues
Merges #153

2020-08-31 13:53 UTC, alexjfisher requested changes
Why have you skipped 5.1.0?

2020-08-31 17:24 UTC, Anirudhra10 commented
Oops, it was an oversight, will push 5.1.0

2020-09-01 12:00 UTC, bastelfreak approved these changes

2020-09-01 12:00 UTC, bastelfreak commented
thanks for the PR. I will merge it and do the release.

2020-09-01 12:00 UTC, merged