Add puppet-strings docs
voxpupuli/puppet-proxysql pull request #156
Opened 2020-10-09 14:24 UTC by baurmatt

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

2020-10-09 14:32 UTC, mcrauwel approved these changes
LGTM... @alexjfisher @bastelfreak any comments here?

2020-10-09 15:55 UTC, bastelfreak approved these changes
LGTM. @alexjfisher same here, should we add puppet-lint-param-docs?

2020-10-10 08:54 UTC, alexjfisher requested changes

2020-10-10 08:54 UTC, alexjfisher commented on manifests/init.pp
>  #   The name of the ProxySQL package in your package manager. Defaults to 'proxysql'
For all parameters that have defaults in init.pp, could you remove the duplicated `Defaults to` stuff from the puppet-strings docs?

2020-10-10 08:55 UTC, alexjfisher commented on manifests/init.pp
> +# @summary This class is called from proxysql for service config.
No, this *is* the proxysql class. :)

2020-10-10 08:57 UTC, alexjfisher commented on REFERENCE.md
> +Default value: `$proxysql::params::version`
In cases like this, we obviously do want to be calling out what the actual default is in the `@param` docs.

2020-10-10 08:58 UTC, alexjfisher commented on REFERENCE.md
> +lint:ignore:2sp_soft_tabs
This isn't great to be appearing in the docs!

2020-10-10 09:03 UTC, alexjfisher commented
@baurmatt Thanks!  Just a couple of things to clean up.

2020-10-10 09:04 UTC, alexjfisher commented
> LGTM. @alexjfisher same here, should we add puppet-lint-param-docs?

Definitely.  For all modules where we get everything documented, lets keep it that way.

2020-10-10 18:12 UTC, baurmatt commented on manifests/init.pp
>  #   The name of the ProxySQL package in your package manager. Defaults to 'proxysql'
Makes sense! :) Fixed!

2020-10-10 18:13 UTC, baurmatt commented on manifests/init.pp
> +# @summary This class is called from proxysql for service config.
hahahahaha :joy: Nice catch! :) Fixed! :)

2020-10-10 18:31 UTC, baurmatt commented on REFERENCE.md
> +lint:ignore:2sp_soft_tabs
:see_no_evil: Fixed! :)

2020-10-14 18:51 UTC, alexjfisher requested changes

2020-10-14 18:51 UTC, alexjfisher commented on .sync.yml
> +  required:
I think you need to use `optional:` and not `required:` otherwise this is the result of running modulesync...
```patch
diff --git a/Gemfile b/Gemfile
index 8592cd6..29a1506 100644
--- a/Gemfile
+++ b/Gemfile
@@ -11,27 +11,7 @@ def location_for(place, fake_version = nil)
 end
 
 group :test do
-  gem 'voxpupuli-test', '~> 2.0',  :require => false
-  gem 'coveralls',                 :require => false
-  gem 'simplecov-console',         :require => false
-end
-
-group :development do
-  gem 'travis',                   :require => false
-  gem 'travis-lint',              :require => false
-  gem 'guard-rake',               :require => false
-  gem 'overcommit', '>= 0.39.1',  :require => false
-end
-
-group :system_tests do
-  gem 'voxpupuli-acceptance',  :require => false
-end
-
-group :release do
-  gem 'github_changelog_generator',  :require => false, :git => 'https://github.com/voxpupuli/github-changelog-generator', :branch => 'voxpupuli_essential_fixes'
-  gem 'puppet-blacksmith',           :require => false
-  gem 'voxpupuli-release',           :require => false
-  gem 'puppet-strings', '>= 2.2',    :require => false
+  gem 'puppet-lint-param-docs',  :require => false
 end
```

2020-10-14 18:55 UTC, baurmatt commented on .sync.yml
> +  required:
Urgh, thanks! :) Changed in all PRs. Is there an easy way to test modulesync for a module?

2020-10-14 18:58 UTC, alexjfisher approved these changes

2020-10-14 19:09 UTC, alexjfisher commented
@baurmatt Thanks!

2020-10-14 19:09 UTC, merged

2020-10-14 21:36 UTC, alexjfisher commented on .sync.yml
> +  required:
Dunno about easy way, but I can share what I did from within modulesync_config
```
bundle exec msync update -f puppet-proxysql --noop
```
then inside of modules/voxpupuli/puppet-proxysql altered .msync.yml, commited the change to that one file with a dummy commit, went back to the root of modulesync_config and ran the `bundle exec msync update -f puppet-proxysql --noop` again.

I suspect there's a much better way...